title: Jamie Hargreaves - Data Engineer
email: jamie_3213@hotmail.com
description: My personal blog where I write about Data Engineering, Cloud and Python
baseurl: /blog
url: jamie3213.github.io
github_username:  jamie3213

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
