title: Your awesome title
email: jamie_3213@hotmail.com
description: ""
baseurl: "/blog" 
url: jamie3213.github.io
github_username:  jamie3213

# Build settings
theme: minima
plugins:
  - jekyll-feed
