title: Jamie Hargreaves
email: jamie_3213@hotmail.com
url: https://blog.jamiehargreaves.co.uk
baseurl: ''
description: Welcome to my blog.
logo: /assets/img/logo.png
github_username:  jamie3213

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
kramdown:
  input: GFM
  toc_levels: 2..2