version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing build dependencies...
      - apt install -y hugo
      - brew install hugo
  build:
    commands:
      - echo Build started on `date`
      - echo Building website...
      - hugo -D
artifacts:
  files:
    - public/**/*
