version: 0.2

phases:
  build:
    commands:
      - echo Deployment started on `date`
      - echo Downloading build artifacts...
      - aws s3 cp s3://$S3_BUILD_BUCKET/blog/build.zip .
      - unzip build.zip -d build
      - echo Deploying build artifacts...
      - aws s3 cp --recursive build/site/app/public s3://$S3_DEPLOY_BUCKET
