version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing build dependencies...
      - wget https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_0.91.2_Linux-64bit.deb
      - dpkg -i hugo_0.91.2_Linux-64bit.deb
      - apt-get -y install
  # build:
  #   commands:
  #     - echo Build started on `date`
  #     - echo Building website...
  #     - cd site/app
  #     - hugo -D