version: 0.2

phases:
  pre-build:
    commands:
      - echo Installing build dependencies...
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - brew install hugo
  build:
    commands:
      - echo Build started on `date`
      - echo Building website...
      - hugo -D
artifacts:
  file:
    - public/**/*
